2022-07-08 11:43:49,284 DEBUG    root            Loaded Command Group: ['gcloud', 'projects']
2022-07-08 11:43:49,291 DEBUG    root            Loaded Command Group: ['gcloud', 'projects', 'get_iam_policy']
2022-07-08 11:43:49,292 DEBUG    root            Running [gcloud.projects.get-iam-policy] with arguments: [PROJECT_ID_OR_NUMBER: "app-translation-on-demand@tradera-development.iam.gserviceaccount.com"]
2022-07-08 11:43:49,309 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2022-07-08 11:43:50,021 DEBUG    urllib3.connectionpool https://cloudresourcemanager.googleapis.com:443 "POST /v1/projects/app-translation-on-demand%40tradera-development.iam.gserviceaccount.com:getIamPolicy?alt=json HTTP/1.1" 400 None
2022-07-08 11:43:50,025 DEBUG    root            (gcloud.projects.get-iam-policy) INVALID_ARGUMENT: Request contains an invalid argument.
Traceback (most recent call last):
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
    resources = command_instance.Run(args)
  File "/opt/google-cloud-sdk/lib/surface/projects/get_iam_policy.py", line 48, in Run
    return projects_api.GetIamPolicy(project_ref)
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/api_lib/cloudresourcemanager/projects_api.py", line 169, in GetIamPolicy
    return client.projects.GetIamPolicy(policy_request)
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/third_party/apis/cloudresourcemanager/v1/cloudresourcemanager_v1_client.py", line 836, in GetIamPolicy
    return self._RunMethod(
  File "/opt/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 737, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
  File "/opt/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 743, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
  File "/opt/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 609, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpBadRequestError: HttpError accessing <https://cloudresourcemanager.googleapis.com/v1/projects/app-translation-on-demand%40tradera-development.iam.gserviceaccount.com:getIamPolicy?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Fri, 08 Jul 2022 09:43:49 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'server-timing': 'gfet4t7; dur=571', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'transfer-encoding': 'chunked', 'status': 400}>, content <{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT"
  }
}
>
2022-07-08 11:43:50,026 ERROR    root            (gcloud.projects.get-iam-policy) INVALID_ARGUMENT: Request contains an invalid argument.
