2022-07-20 10:03:33,222 DEBUG    root            Loaded Command Group: ['gcloud', 'compute']
2022-07-20 10:03:33,224 DEBUG    root            Loaded Command Group: ['gcloud', 'compute', 'ssl_certificates']
2022-07-20 10:03:33,254 DEBUG    root            Loaded Command Group: ['gcloud', 'compute', 'ssl-certificates', 'list']
2022-07-20 10:03:33,256 DEBUG    root            Running [gcloud.compute.ssl-certificates.list] with arguments: [--global: "True"]
2022-07-20 10:03:45,449 DEBUG    google.auth.transport.requests Making request: POST https://oauth2.googleapis.com/token
2022-07-20 10:03:45,450 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): oauth2.googleapis.com:443
2022-07-20 10:03:45,661 DEBUG    urllib3.connectionpool https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
2022-07-20 10:03:45,962 INFO     root            Display format: "    table(
      name,
      type,
      creationTimestamp,
      expireTime,
      managed.status:label=MANAGED_STATUS,
      managed.domainStatus:format="yaml"
    )"
2022-07-20 10:03:45,964 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): compute.googleapis.com:443
2022-07-20 10:03:46,439 DEBUG    urllib3.connectionpool https://compute.googleapis.com:443 "POST /batch/compute/v1 HTTP/1.1" 200 None
2022-07-20 10:03:54,261 DEBUG    root            (gcloud.compute.ssl-certificates.list) PERMISSION_DENIED: Compute Engine API has not been used in project 371183367591 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=371183367591 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
- '@type': type.googleapis.com/google.rpc.Help
  links:
  - description: Google developers console API activation
    url: https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=371183367591
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: googleapis.com
  metadatas:
    consumer: projects/371183367591
    service: compute.googleapis.com
  reason: SERVICE_DISABLED
Traceback (most recent call last):
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 811, in Run
    display_info=self.ai.display_info).Display()
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/calliope/display.py", line 483, in Display
    self._printer.Print(self._resources)
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/core/resource/resource_printer_base.py", line 298, in Print
    for resource in resources:
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/core/util/peek_iterable.py", line 211, in __next__
    item = self._NextItem()
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/core/util/peek_iterable.py", line 183, in _NextItem
    return next(self._iterable)
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/lister.py", line 1120, in __call__
    for item in request_helper.ListJson(
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/request_helper.py", line 231, in ListJson
    for item in _ListCore(requests, http, batch_url, errors, _HandleJsonList):
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/request_helper.py", line 139, in _ListCore
    responses, request_errors = batch_helper.MakeRequests(
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/batch_helper.py", line 104, in MakeRequests
    responses = batch_request.Execute(
  File "/opt/google-cloud-sdk/lib/third_party/apitools/base/py/batch.py", line 226, in Execute
    batch_http_request.Execute(http)
  File "/opt/google-cloud-sdk/lib/third_party/apitools/base/py/batch.py", line 506, in Execute
    self.__callback(response, exception)
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/batch_helper.py", line 72, in BatchCheck
    apis.PromptToEnableApi(project, service_token, exception,
  File "/opt/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis.py", line 193, in PromptToEnableApi
    raise exception
googlecloudsdk.api_lib.util.exceptions.HttpException: PERMISSION_DENIED: Compute Engine API has not been used in project 371183367591 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=371183367591 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
- '@type': type.googleapis.com/google.rpc.Help
  links:
  - description: Google developers console API activation
    url: https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=371183367591
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: googleapis.com
  metadatas:
    consumer: projects/371183367591
    service: compute.googleapis.com
  reason: SERVICE_DISABLED
2022-07-20 10:03:54,263 ERROR    root            (gcloud.compute.ssl-certificates.list) PERMISSION_DENIED: Compute Engine API has not been used in project 371183367591 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=371183367591 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
- '@type': type.googleapis.com/google.rpc.Help
  links:
  - description: Google developers console API activation
    url: https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=371183367591
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: googleapis.com
  metadatas:
    consumer: projects/371183367591
    service: compute.googleapis.com
  reason: SERVICE_DISABLED
